version: "3.8"

services:
  site-collaba:
    container_name: site-collaba
    environment:
      - TZ="Europe/Moscow"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3003:3000"
    restart: always
