FROM node:18-alpine

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci --only=production

# Копируем исходный код
COPY . .

# Собираем приложение
RUN npm run build

# Открываем порт для WebSocket сервера
EXPOSE 7000

# Запускаем приложение
CMD ["npm", "run", "start:prod"]
